Allow to skip database creation
temporalio/helm-charts pull request #480
Opened 2024-04-09 14:34 UTC by VLZZZ

## What was changed

This PR adds an ability to skip database creation. The default values ensures that the change will be backwards compatible with an existing installations.
## Why?

Currently it's not possible to use already existing database when deploying Temporal using this Helm chart
## Checklist

1. Closes 

# 440
2. How was this tested:

I've ruined a clean install with:
```
schema:
  createDatabase:
    enabled: false
```

3. Any docs updates needed?

2024-04-09 14:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/temporalio/helm-charts?pullRequest=480) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/temporalio/helm-charts?pullRequest=480) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/temporalio/helm-charts?pullRequest=480) it.</sub>

2024-05-08 05:31 UTC, zaenk commented
I just wanted to do this exact same thing! Thanks for opening this PR!

2024-06-08 14:57 UTC, robholland requested changes

2024-06-08 14:57 UTC, robholland commented on charts/temporal/Chart.yaml
> +version: 0.37.0
Please revert this change, the version is bumped automatically by our tooling.

2024-06-14 07:29 UTC, robholland approved these changes

2024-06-14 07:31 UTC, robholland commented
Thanks for your contribution :) For future reference: if you make changes to address PR feedback, if you re-request feedback from the relevant person, it makes it more obvious the PR is ready for review again.

2024-06-14 07:31 UTC, merged