Update Cassandra host URLs to remove the ".cluster.local" suffix
temporalio/helm-charts pull request #485
Opened 2024-05-01 18:31 UTC by cege7480

## What was changed
No longer hardcoding the cluster.local suffix on various service reference entries.

## Why?
Hardcoding breaks when the cluster name isn't cluster.local.
Relative path will work unless you've done something super weird with your dns.
## Checklist

1. Closes #469 

2. How was this tested:
Ran the helm chart...  installed.  Boom.  
Successfully able to resolve using relative domain names.

3. Any docs updates needed?
Nah.

2024-05-01 18:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/temporalio/helm-charts?pullRequest=485) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/temporalio/helm-charts?pullRequest=485) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/temporalio/helm-charts?pullRequest=485) it.</sub>

2024-06-08 14:52 UTC, robholland requested changes
Please remove the devcontainer and dependabot files, they are not related to this change.

2024-06-12 22:41 UTC, cege7480 commented
> Please remove the devcontainer and dependabot files, they are not related to this change.

Sorry about that.

2024-06-14 07:33 UTC, robholland approved these changes

2024-06-14 07:34 UTC, robholland commented
Thanks for your contribution :)

2024-06-14 07:35 UTC, merged