Update job to create default namespace
temporalio/helm-charts pull request #550
Opened 2024-08-27 04:10 UTC by mananmangal

## What was changed

Update the server setup Kubernetes job to create a default namespace.
Create configuration to enable this feature, by default its disabled.
Also, provides option to configure retention period, by default its 3 days.

## Why?

Creates a default namespace on the server to avoid manual effort.

## Checklist

1. Closes [420](https://github.com/temporalio/helm-charts/issues/420)

2. How was this tested:  Manual installation of the helm chart and running the updated job on a Kubernetes cluster to validate creation of new namespace.

3. Any docs updates needed?

2024-08-27 04:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/temporalio/helm-charts?pullRequest=550) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/temporalio/helm-charts?pullRequest=550) before we can accept your contribution.<br/><hr/>**Manan Mangal** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/temporalio/helm-charts?pullRequest=550) it.</sub>

2024-09-02 11:46 UTC, robholland requested changes
Please adjust to take a list of namespaces rather than just one. Probably as a list of maps, so they can set the namespace name and (optionally) retention per namespace.

2024-09-10 22:35 UTC, trin4ik commented
the right thing, I need it.

2024-09-25 07:53 UTC, robholland requested changes

2024-09-25 07:53 UTC, robholland commented on charts/temporal/values.yaml
> +    defaultNamespaces:
```suggestion
    namespaces:
```

2024-09-25 07:53 UTC, robholland commented on charts/temporal/values.yaml
> +      enabled: false
```suggestion
      create: false
```

2024-09-25 17:54 UTC, mananmangal commented on charts/temporal/values.yaml
> +    defaultNamespaces:
Applied this change

2024-09-25 17:54 UTC, mananmangal commented on charts/temporal/values.yaml
> +      enabled: false
Applied this change

2024-09-26 16:23 UTC, robholland approved these changes

2024-09-26 16:24 UTC, robholland commented
I'm on the fence about whether this should happen only if we have `schema.create/update` turned on, but I can revisit that. Thanks for you contribution :)

2024-09-26 16:24 UTC, merged