Add support for TLS-enabled Cassandra configurations
temporalio/helm-charts pull request #552
Opened 2024-09-03 22:31 UTC by ghaskins

## What was changed

We add support for TLS-enabled Cassandra-based persistence stores.

## Why?

Production best practices prescribe TLS-enabled connections wherever available, and Cassandra databases offer this feature.  This patch allows consumers of the Temporal helm-chart to configure TLS-enabled Cassandra clusters as a persistence store using established idioms such as additionalVolume configuration.  We also extend the mechanism for setting admintools environment variables like TLS support for SQL databases.

2024-12-04 14:28 UTC, robholland commented
Sorry for the delay here, please re-base and I'll get this merged.

2024-12-11 17:16 UTC, robholland requested changes
Please re-base.

2024-12-11 18:56 UTC, ghaskins commented
@robholland I used the GH UI interface to resolve the conflcts, and it created a merge-record.  If accepted, please squash-merge this PR. I'm happy to re-do it on my workstation if preferred.  Ty!

2024-12-16 14:24 UTC, robholland approved these changes

2024-12-16 14:24 UTC, merged