Config to specify tags to be excluded in prometheus metrics
temporalio/helm-charts pull request #566
Opened 2024-09-26 18:00 UTC by prathyushpv

## Why?
Config to exclude metrics tags from prometheus.

## Checklist

1. Closes

2. How was this tested:

3. Any docs updates needed?

2024-09-27 11:05 UTC, robholland requested changes

2024-09-27 11:05 UTC, robholland commented on charts/temporal/templates/server-configmap.yaml
> +          {{- end }}
```suggestion
        {{- with $server.metrics.excludeTags }}
        excludeTags:
          {{- toYaml . | nindent 10 }}
        {{- end }}
```

2024-09-27 11:05 UTC, robholland commented on charts/temporal/templates/server-configmap.yaml
> +          {{- end }}
Avoid adding an empty `excludeTags` block.

2024-09-27 17:10 UTC, prathyushpv commented
Thanks Rob! I have applied the suggested change.

2024-09-30 10:40 UTC, robholland approved these changes

2024-09-30 10:40 UTC, merged